# Generated by Django 5.1.2 on 2024-11-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.RemoveField(
            model_name='networkunit',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='networkunit',
            name='city',
        ),
        migrations.RemoveField(
            model_name='networkunit',
            name='country',
        ),
        migrations.RemoveField(
            model_name='networkunit',
            name='street',
        ),
        migrations.RemoveField(
            model_name='product',
            name='network_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', to='network.networkunit', verbose_name='Поставщики'),
        ),
        migrations.AddField(
            model_name='networkunit',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_units', to='network.address', verbose_name='Адрес'),
        ),
    ]
